#from pandas import Series, DataFrame
from pandas import Series
import pandas

d = Series(["--","--","--","--","--","--","--","--","--","--","--","--","--","--","--"], 
index = ["LogType","TotalStepNum", "CycleNum", "Re_calculate", "CycleStepNum", "CycleNum_CycleCool", "CycleStepNum_CycleCool", "FillError", "AnalysisResult", "Warning", "WarningMessage", "Error", "ErrorMessage", "FillErrorStepNum", "MDXVersion"])

def WriteOutPut(writeType,writeContent):
  d[writeType] = writeContent
print str(d["LogType"])
def WriteResult():
  file = open('C:\\WorkingFolder\\testCase\\ManualFeatureTable.txt', 'w')
  file.write("Log Type: "+str(d["LogType"]))
  file.write("\n")
  file.write("Analysis Result: "+str(d["AnalysisResult"]))
  file.write("\n")
  file.write("Warning: "+str(d["Warning"]))
  file.write("\n")
  file.write("Warning Message: "+str(d["WarningMessage"]))
  file.write("\n")
  file.write("Error: "+str(d["Error"]))
  file.write("\n")
  file.write("Error Message: "+str(d["ErrorMessage"]))
  file.write("\n")
  file.write("Re Calculate: "+str(d["Re_calculate"]))
  file.write("\n")
  file.write("Total Step Num: "+str(d["TotalStepNum"]))
  file.write("\n")
  file.write("Cycle Num(CycleCool): "+str(d["CycleNum_CycleCool"]))
  file.write("\n")
  file.write("Cycle Step Num(CycleCool): "+str(d["CycleStepNum_CycleCool"]))
  file.write("\n")
  file.write("Cycle Num(TransientCool): "+str(d["CycleNum"]))
  file.write("\n")
  file.write("Cycle Step Num(TransientCool): "+str(d["CycleStepNum"]))
  file.write("\n")
  file.write("Fill Percentage Discontinuous: "+str(d["FillError"]))
  file.write("\n")
  file.write("Discontinuous At Step Num: "+str(d["FillErrorStepNum"]))
  file.write("\n")
  file.write("MDXVersion: "+str(d["MDXVersion"]))
  file.write("\n")
  file.close()

def WriteResult_AutoTest():
  file = open('C:\\WorkingFolder\\testCase\\AutoTestFeatureTable.txt', 'w')
  file.write("Log Type: "+str(d["LogType"]))
  file.write("\n")
  file.write("Analysis Result: "+str(d["AnalysisResult"]))
  file.write("\n")
  file.write("Warning: "+str(d["Warning"]))
  file.write("\n")
  file.write("Warning Message: "+str(d["WarningMessage"]))
  file.write("\n")
  file.write("Error: "+str(d["Error"]))
  file.write("\n")
  file.write("Error Message: "+str(d["ErrorMessage"]))
  file.write("\n")
  file.write("Re Calculate: "+str(d["Re_calculate"]))
  file.write("\n")
  file.write("Total Step Num: "+str(d["TotalStepNum"]))
  file.write("\n")
  file.write("Cycle Num(CycleCool): "+str(d["CycleNum_CycleCool"]))
  file.write("\n")
  file.write("Cycle Step Num(CycleCool): "+str(d["CycleStepNum_CycleCool"]))
  file.write("\n")
  file.write("Cycle Num(TransientCool): "+str(d["CycleNum"]))
  file.write("\n")
  file.write("Cycle Step Num(TransientCool): "+str(d["CycleStepNum"]))
  file.write("\n")
  file.write("Fill Percentage Discontinuous: "+str(d["FillError"]))
  file.write("\n")
  file.write("Discontinuous At Step Num: "+str(d["FillErrorStepNum"]))
  file.write("\n")
  file.write("MDXVersion: "+str(d["MDXVersion"]))
  file.write("\n")
  file.close()

